In [3]:
from rich.console import Console
import torch
from torch import nn
console = Console()

## Copy Weight Between Modules

In [10]:
a = nn.Linear(4, 3)
b = nn.Linear(4, 3)
console.print('--- [yellow]Weight of module a[/] ---')
console.print(a.weight)
console.print('--- [yellow]Weight of module b[/] ---')
console.print(b.weight)
a(torch.randn(10, 4)).sum().backward()
console.print('--- [yellow]Grad of module a\'s weight[/] ---')
console.print(a.weight.grad)
with torch.no_grad():
    b.weight.copy_(a.weight)
console.print('--- [yellow]Weight of module b after copying[/] ---')
console.print(b.weight)
console.print('--- [yellow]Grad of b\'s weight after copying (still None)[/] ---')
console.print(b.weight.grad)

--- Weight of module a ---

Parameter containing:
tensor([[-0.0692, -0.2555, -0.2303, -0.3956],
        [ 0.2600, -0.4306,  0.1944, -0.1055],
        [-0.4039,  0.3127,  0.1193,  0.0619]], requires_grad=True)

--- Weight of module b ---

Parameter containing:
tensor([[ 0.2168, -0.4786,  0.2107,  0.3373],
        [ 0.1556, -0.3197, -0.4132, -0.4751],
        [ 0.0275, -0.1506, -0.2630,  0.1806]], requires_grad=True)

--- Grad of module a's weight ---

tensor([[-6.6695, -4.6779,  1.5673,  1.6921],
        [-6.6695, -4.6779,  1.5673,  1.6921],
        [-6.6695, -4.6779,  1.5673,  1.6921]])

--- Weight of module b after copying ---

Parameter containing:
tensor([[-0.0692, -0.2555, -0.2303, -0.3956],
        [ 0.2600, -0.4306,  0.1944, -0.1055],
        [-0.4039,  0.3127,  0.1193,  0.0619]], requires_grad=True)

--- Grad of b's weight after copying (still None) ---

None